[versions]
kotlin = "2.3.21"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
junit = "6.0.3"
strikt = "0.35.1"
flyway = "12.6.0"
springFramework = "7.0.0"
testcontainers = "2.0.5"
hikariCP = "7.0.2"
postgresql = "42.7.11"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }
flyway-databasePostgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "springFramework" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikariCP" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
jvmTest-implementation = ["junit-jupiter", "strikt-core"]
jvmTest-runtime = ["junit-platform-launcher"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
